// Auto-generated by update-changelog.sh — do not edit manually
// Source: CHANGELOG.md

const CHANGELOG = [
  {
    "version": "v0.4.4",
    "date": "2026-04-05",
    "changes": [
      "Rework NPC shadowing: true time-based temporal following in all phases (approaching, following, talking, reacting, leaving) — NPC always sits at the player's world position from 0.17 s ago, no camera locking anywhere; screen distance stretches at high speed and compresses at low speed naturally"
    ]
  },
  {
    "version": "v0.4.0",
    "date": "2026-04-05",
    "changes": [
      "Introduce changelog file and version history panel in Settings",
      "Add script to generate changelog data from markdown source"
    ]
  },
  {
    "version": "v0.3.1",
    "date": "2026-04-05",
    "changes": [
      "Redesign platforms with 5 seamless kinds and per-kind decorations",
      "Platform kinds now vary between 6–11 per biome run",
      "Explicit Save button at bottom of character editor",
      "Fix Firebase init crash on settings load"
    ]
  },
  {
    "version": "v0.3.0",
    "date": "2026-04-05",
    "changes": [
      "YouTube music playback during gameplay",
      "Redesign settings page with modern iOS-style UX"
    ]
  },
  {
    "version": "v0.2.0",
    "date": "2026-04-05",
    "changes": [
      "Jump immediately on landing if jump is still held",
      "Pause button, home button and back navigation in-game",
      "Better settings icon",
      "Show version date alongside version on game cover",
      "NPC only triggers when it has configured interactions",
      "NPC follows player's exact path instead of mirroring Y instantly",
      "Redesign NPC as shadow-player that approaches, follows, then leaves"
    ]
  },
  {
    "version": "v0.1.0",
    "date": "2026-03-30",
    "changes": [
      "Per-character interaction CRUD in settings, used in-game",
      "Balance difficulty: NPC-driven speed, easier split paths",
      "Rebrand cover screen to Daglezja garden centre identity",
      "Increase NPC encounter frequency",
      "Character management: custom images per mood, Firebase sync",
      "Settings page as full-screen HTML overlay with light theme",
      "Add jump buffer — tap just before landing queues the jump",
      "Gameplay sliders and modular file split"
    ]
  },
  {
    "version": "v0.0.x",
    "date": "2026-03-29",
    "changes": [
      "Initial prototype: runner game with NPC dialogue and choice paths",
      "NPC question spawns two coloured paths; player answers by running one",
      "Pause menu and settings screen with version display",
      "Character select with mood images and colour themes",
      "Firebase Storage integration for cloud character sync"
    ]
  }
];
