#!/usr/bin/env bash
# update-changelog.sh — parse CHANGELOG.md and generate js/changelog.js
# Run this before deploying to keep the in-game version history up to date.

set -euo pipefail

CHANGELOG_MD="$(dirname "$0")/CHANGELOG.md"
OUTPUT_JS="$(dirname "$0")/js/changelog.js"

if [[ ! -f "$CHANGELOG_MD" ]]; then
  echo "Error: CHANGELOG.md not found at $CHANGELOG_MD" >&2
  exit 1
fi

# Parse CHANGELOG.md into structured JS.
# Expected format per version block:
#   ## [vX.Y.Z] - YYYY-MM-DD
#   - change one
#   - change two
#
# Blocks are separated by blank lines before the next ## heading.

python3 - "$CHANGELOG_MD" "$OUTPUT_JS" <<'PYEOF'
import sys, re, json

md_path, js_path = sys.argv[1], sys.argv[2]

with open(md_path, encoding='utf-8') as f:
    content = f.read()

entries = []
# Split on version headings
blocks = re.split(r'\n(?=## \[)', content)
for block in blocks:
    header = re.match(r'## \[([^\]]+)\]\s*-\s*(\S+)', block)
    if not header:
        continue
    version, date = header.group(1), header.group(2)
    changes = re.findall(r'^- (.+)', block, re.MULTILINE)
    entries.append({'version': version, 'date': date, 'changes': changes})

lines = ['// Auto-generated by update-changelog.sh — do not edit manually',
         '// Source: CHANGELOG.md',
         '',
         'const CHANGELOG = ' + json.dumps(entries, ensure_ascii=False, indent=2) + ';']

with open(js_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"Generated {js_path} with {len(entries)} version entries.")
PYEOF
